jobs:
  setup:
    outputs:
      techdocs: ${{ steps.changes.outputs.techdocs == 'true' || steps.changes.outputs.workflows == 'true' }}

  techdocs:
    needs: setup
    if: needs.setup.outputs.techdocs == 'true'
    concurrency:
      group: ${{ github.repository }}-${{ github.workflow }}-techdocs-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      id-token: write
      packages: read
      pull-requests: read
    uses: coopnorge/github-workflow-techdocs/.github/workflows/techdocs.yaml@v0

  validate-ci-results:
    needs:
      - techdocs
