name: Validate policy-bot config file

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      policy-bot-config-path:
        type: string
        default: .policy.yml
        required: false
        description: |
          Relative path of policy-bot config file. Defaults to `.policy.yml`.
      policy-bot-server-url:
        type: string
        required: true
        description: |
          Base url where policy bot is available.

defaults:
  run:
    shell: bash

jobs:
  validate-policy-bot-config:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate policy-bot config
        run: |
          set -euo pipefail
          policy_bot_server_url="${{ inputs.policy-bot-server-url }}"
          policy_bot_server_url="${policy_bot_server_url%/}/"
          echo "Uploading ${{ inputs.policy-bot-config-path }} to ${policy_bot_server_url}api/validate"
          response_code=$(
            curl --silent \
              "${policy_bot_server_url}api/validate" \
              --request PUT \
              --upload-file "${{ inputs.policy-bot-config-path }}" \
              --write-out "%{http_code}" \
              --output response.json
            )
          message=$(jq '.message' response.json)

          if [[ $response_code -ne 200 ]]; then
            echo "::error::$message"
            exit 1
          fi

          echo "::notice::$message"
